### ISSUE TITLE
Number of nodes bug in checkScript

### ISSUE THREAD

**Issue by gpsgibb** [aturner-epcc/epcc-archer-tools#1]
If a user's PBS script requests more than the maximum number of nodes (4920) then the script crashes without printing the "too many nodes requested" error message. 

This is because the maxtime variable is set to a blank string but not populated (as node counts are invalid so nothing is set in the end - lines 179-195). This results in an exception at line 198 when trying to obtain the maximum walltime in seconds via the function timeToSeconds() as it cannot handle an empty string.

As checkScript queues up errors with the PBS script and prints them at the end of checkScript, due to the exception occurring halfway through, no errors are printed out.

**Comment by aturner-epcc** [comment]
@gpsgibb Thanks. The limit on nodes in the long queue has been raised to 256 nodes so this needs changed in the script too.

**Comment by gpsgibb** [comment]
Created pull request for the fix

**Comment by aturner-epcc** [comment]
Thanks @gpsgibb
